# Generated by Django 5.2.8 on 2026-02-16 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Status 0'), (1, 'Status 1')])),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'db_table': 'events_calendarevent',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('image', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('artist', models.TextField()),
                ('cost', models.PositiveIntegerField(default=0)),
                ('currency', models.TextField(default='KZT')),
                ('category', models.IntegerField(choices=[(0, 'Category 0'), (1, 'Category 1'), (2, 'Category 2'), (3, 'Category 3')])),
                ('address', models.TextField()),
                ('link', models.TextField()),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events_event',
            },
        ),
        migrations.CreateModel(
            name='EventTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', models.IntegerField(choices=[(0, 'Language 0'), (1, 'Language 1'), (2, 'Language 2'), (3, 'Language 3')])),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Event Translation',
                'verbose_name_plural': 'Event Translations',
                'db_table': 'events_eventtranslation',
            },
        ),
    ]
