# Generated by Django 5.2.8 on 2026-02-16 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['deleted_at'], name='idx_event_deleted_at'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventtranslation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='events.event'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['user'], name='idx_calendar_user'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['event'], name='idx_calendar_event'),
        ),
        migrations.AlterUniqueTogether(
            name='calendarevent',
            unique_together={('user', 'event')},
        ),
        migrations.AddIndex(
            model_name='eventtranslation',
            index=models.Index(fields=['event'], name='idx_eventtrans_event'),
        ),
        migrations.AlterUniqueTogether(
            name='eventtranslation',
            unique_together={('event', 'language_id')},
        ),
    ]
