# Generated by Django 5.2.8 on 2025-12-21 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='store_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.storeproductrelation', verbose_name='Product'),
        ),
    ]
