services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      PROJECT_ENV_ID: prod
      DJANGO_SETTINGS_MODULE: settings.env.prod
    volumes:
      - static_data:/app/static
      - media_data:/app/media
      - sqlite_data:/app/data
    expose:
      - "8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - static_data:/static:ro
      - media_data:/media:ro
    depends_on:
      - backend

volumes:
  static_data:
  media_data:
  sqlite_data:
