# Generated by Django 5.2.8 on 2026-05-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementtranslation',
            name='language_id',
            field=models.IntegerField(choices=[(0, 'Language 0'), (1, 'Language 1'), (2, 'Language 2'), (3, 'Language 3'), (4, 'Language 4'), (5, 'Language 5'), (6, 'Language 6')]),
        ),
    ]
