# Generated by Django 5.2.8 on 2026-05-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_advertisementtranslation_language_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='link',
            field=models.TextField(blank=True, default=''),
        ),
    ]
