# Generated by Django 5.2.8 on 2026-02-16 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('image', models.TextField()),
                ('category', models.IntegerField(choices=[(0, 'Category 0'), (1, 'Category 1'), (2, 'Category 2'), (3, 'Category 3')])),
                ('address', models.TextField()),
                ('link', models.TextField()),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
                'db_table': 'places_place',
                'indexes': [models.Index(fields=['deleted_at'], name='idx_place_deleted_at')],
            },
        ),
        migrations.CreateModel(
            name='PlaceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', models.IntegerField(choices=[(0, 'Language 0'), (1, 'Language 1'), (2, 'Language 2'), (3, 'Language 3')])),
                ('name', models.TextField()),
                ('timetable', models.TextField()),
                ('description', models.TextField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='places.place')),
            ],
            options={
                'verbose_name': 'Place Translation',
                'verbose_name_plural': 'Place Translations',
                'db_table': 'places_placetranslation',
                'indexes': [models.Index(fields=['place'], name='idx_placetrans_place')],
                'unique_together': {('place', 'language_id')},
            },
        ),
    ]
