# Generated by Django 5.2.8 on 2026-04-07 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_latitude_place_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='longitude',
            new_name='lng',
        ),
    ]
