# Generated by Django 5.2.8 on 2026-02-16 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'db_table': 'info_advertisement',
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'Apps',
                'db_table': 'info_app',
            },
        ),
        migrations.CreateModel(
            name='Souvenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('link', models.TextField()),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Souvenir',
                'verbose_name_plural': 'Souvenirs',
                'db_table': 'info_souvenir',
            },
        ),
        migrations.CreateModel(
            name='AdvertisementTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', models.IntegerField(choices=[(0, 'Language 0'), (1, 'Language 1'), (2, 'Language 2'), (3, 'Language 3')])),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='info.advertisement')),
            ],
            options={
                'verbose_name': 'Advertisement Translation',
                'verbose_name_plural': 'Advertisement Translations',
                'db_table': 'info_advertisementtranslation',
                'indexes': [models.Index(fields=['advertisement'], name='idx_adtrans_ad')],
                'unique_together': {('advertisement', 'language_id')},
            },
        ),
    ]
